# Generated by Django 5.0.1 on 2024-01-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description2',
        ),
    ]
