# Generated by Django 5.0.1 on 2024-01-11 16:43

import django.db.models.deletion
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('additional_description', models.CharField(max_length=1000)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=product.models.generate_unique_filename)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=product.models.generate_unique_filename)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=product.models.generate_unique_filename)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=product.models.generate_unique_filename)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.vendor')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varient_details', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='variations',
            field=models.ManyToManyField(related_name='products', to='product.variation'),
        ),
    ]
