# Generated by Django 5.0.1 on 2024-01-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_variation_product_variations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='product',
        ),
    ]
