# Generated by Django 5.0.1 on 2024-02-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_bike_delete_status_category_delete_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='sku',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
