# Generated by Django 5.0.1 on 2024-02-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_variation_price_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='has_offer',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='offer_price',
        ),
        migrations.AddField(
            model_name='product',
            name='has_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
