# Generated by Django 5.0.1 on 2024-02-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_variation_has_offer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='is_featured',
        ),
    ]
