# Generated by Django 5.0.1 on 2024-02-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_productimage_alt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
