# Generated by Django 5.0.1 on 2024-02-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerenoughadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='logo',
        ),
        migrations.AddField(
            model_name='owner',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicons/'),
        ),
        migrations.AddField(
            model_name='owner',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='owner',
            name='website_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
