# Generated by Django 5.0.1 on 2024-02-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerenoughadmin', '0002_remove_owner_logo_owner_favicon_owner_footer_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
